UNICODE_STRINGS = [
    # English meaningful
    "Hello World!",
    "Learning Unicode",
    "Python is fun",
    "Unicode Encoding",
    "Text and Symbols",
    "Data Science 101",
    "Artificial Mind",
    "Space Mission 42",
    "Digital Future",
    "Keep coding!",
    # Arabic meaningful
    "مرحبا بالعالم",
    "تعلم يونيكود",
    "البرمجة ممتعة",
    "ترميز النصوص",
    "علوم البيانات",
    "الذكاء الاصطناعي",
    "المستقبل رقمي",
    "التعلم العميق",
    "حاسوب سريع",
    "ابحث عن المعرفة",
    # Mixed English + Arabic
    "Hello مرحبا",
    "AI ذكاء اصطناعي",
    "Python بايثون",
    "Code كود",
    "Text نصوص",
    "Future مستقبل",
    "Math رياضيات",
    "Science علوم",
    "Vision رؤية",
    "School مدرسة",
    # Random-ish English
    "xYz!42&data",
    "Qwerty123##",
    "Sample_Text!!",
    "MixItUp_99",
    "Ucode-777",
    "learn2WIN$$",
    "Go!Go!123",
    "Try_Unicode",
    "abcXYZ789",
    "Cool++Code",
    # Random-ish Arabic
    "١٢٣٤٥٦٧٨٩٠",
    "رمز@كلمة!",
    "أبجد_هوز",
    "كود++تجربة",
    "نصوص؟بيانات",
    "مرحبا#123",
    "برمجة$$",
    "مستقبل2025",
    "لغة!!عربية",
    "علوم_١٠١",
    # More meaningful English
    "Machine Power",
    "Learn Arabic",
    "Smart Device",
    "Digital Cloud",
    "Happy Coding",
    "Data Mining",
    "Open Source",
    "Quantum Leap",
    "Bright Future",
    "Stay Curious",
    # More meaningful Arabic
    "تعلم اللغة",
    "حاسوب ذكي",
    "برامج مفتوحة",
    "قفزة كمية",
    "ابق فضوليا",
    "شمس مشرقة",
    "فكرة جديدة",
    "طاقة متجددة",
    "رحلة فضائية",
    "ابدأ اليوم",
    # Mixed short phrases
    "AI  ذكاء",
    "Rocket صاروخ",
    "Book كتاب",
    "Light نور",
    "Life حياة",
    "Code شيفرة",
    "Sky سماء",
    "Art فن",
    "Peace سلام",
    "Hope أمل",
    # Random mixed junk
    "abc123!مرح",
    "تجربة@@!!",
    "Mix++مزج",
    "###123###",
    "HELLO---مرح",
    "WOW!!رائع",
    "Good&سيء",
    "++123++",
    "نجاح&&WIN",
    "Fail خسارة",
]
ASCII_STRINGS = [
    # Senseful strings
    "Hello_World!",
    "Learn ASCII fast",
    "Encode & Decode",
    "Base Convert 88",
    "Study-Hard_Today",
    "Python is Great",
    "ASCII Practice 1",
    "Digital Logic 77",
    "Binary-to-Hex",
    "Train Your Mind",
    "Good Morning All",
    "Smart Study Plan",
    "Text_Sample=99",
    "Random Words Set",
    "Decode Me Now!",
    "OpenAI_Tools v2",
    "Simple Example X",
    "School Project 1",
    "Lesson Number 12",
    "Practice Zone 25",
    "Learn by Doing",
    "Fun Learning 44",
    "Python Course X",
    "Open Book Mode",
    "Quiz_Maker 2025",
    "Study Session #2",
    "Numbers Only 42",
    "Edu_Project Lab",
    "Smart Code Plan",
    "Binary Logic Fun",
    "Digital World 1",
    "Train With ASCII",
    "Text Pattern 77",
    "Math Solver 88",
    "Hello Again 25",
    "Decode ASCII Now",
    "Smart Lesson 01",
    "School_Work Set",
    "Test Input Case",
    "Open Lab 88",
    "Hello ASCII 25",
    "Study Case 2025",
    "Practice Makes Perfect",
    "Learn Fast Now!",
    "Encode This Text",
    "Lesson Sample 22",
    "Train Logic Skills",
    "Decode Message 77",
    "Fun With Binary",
    "Learning Never Ends",
    # Random noise strings
    "@c8]rT_2Wl%9",
    "z$Q0J{v#tX}?",
    "4]c@2Xx{W1R!",
    "Vh3@qP]1%$#",
    "*mZ7u=O^rK~",
    "1!v^p4oC=Gh*",
    "kP_3#d&F>JQ",
    "(sU!0Fj=)L8^",
    "5a=K8ZpE+R2%",
    "Wl%9U^&2t#R",
    "nCZ@#7kQ$2!",
    "^F0]B!9eX+u",
    "r$L6m%]V9s{",
    "oT]9!+Jz*Qh",
    "9d{=Y#tQ8w)",
    "*N!4cV$3z]M",
    "%R2=J+fX1h(",
    "H8]oC^k3@V?",
    "u&Q!7^mTz9$",
    "|s_3=Lp#2F<",
    "Z]t8@qR$w4%",
    "cV^!7nX=1b*",
    "jP&9#oT^Q3z",
    "!Y7w_2f@K$R",
    "4x#H9uC=V!q",
    "?M!2oX+f%8Z",
    "vP]1@tQ#9r$",
    "=R4nY^k3w!J",
    "Lp#1cU=9^z(",
    "5h*Zt%Q2+oR",
    "u_7C!@jX^9&",
    "B]1qP#3=V$k",
    "xTz@9!fM=7w",
    "?Q2u+oR^5c#",
    "^k3W8t%R=1z",
    "L9oP#@7^q=F",
    "2j*Xv!Q#h=5",
    "R$8nY@c^2t!",
    "vC=1qU#9@Z)",
    "H7+oT^4!fM%",
    "s_9=Q2j@p#R",
    "|t3wX^8c+V!",
    "oR$2nY=5^k#",
    "M!1j*Q9+oT^",
    "Lp=7wX%R@4c",
    "?V9^k3q#1tO",
    "xC=2u+R^5f@",
    "P]1z*L#9w=Q",
    "H7oT^!3+M%f",
    "2vC@5n=1q^Z",
]
