#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  bool_const.py
#  
#  Copyright 2021 zerrouki <zerrouki@majd4>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

TEX_REDUCTION_TABLE ={
    # one variable
    "a": "\\implicant{12}{10}",
    "a'": "\\implicant{0}{6}",
    "b":"\\implicant{4}{14}",
    "b'": "\\implicantedge{0}{2}{8}{10}",
    "c":"\\implicant{3}{10}",
    "c'":"\\implicant{0}{9}",
    "d":"\\implicant{1}{11}",
    "d'": "\\implicantedge{0}{8}{2}{10}", 
    # two variables
    #a
     "a.b": "\\implicant{12}{14}",     
     "a.b'": "\\implicant{8}{10}",     
     "a.c": "\\implicant{15}{10}",     
     "a.c'": "\\implicant{12}{9}",     
     "a.d": "\\implicant{13}{11}",     
     "a.d'": "\\implicantedge{12}{8}{14}{10}", 
     #a'     
     "a'.b": "\\implicant{4}{6}",     
     "a'.b'": "\\implicant{0}{2}",     
     "a'.c": "\\implicant{3}{6}",     
     "a'.c'": "\\implicant{0}{5}",     
     "a'.d": "\\implicant{1}{7}",     
     "a'.d'": "\\implicantedge{0}{4}{2}{6}",  
     # b       
     "b.c": "\\implicant{7}{14}",     
     "b.c'": "\\implicant{4}{13}",     
     "b.d": "\\implicant{5}{15}",     
     "b.d'": "\\implicantedge{4}{12}{6}{14}", 
    # b'
     "b'.c": "\\implicantedge{3}{2}{11}{10}",     
     "b'.c'": "\\implicantedge{0}{1}{8}{9}",     
     "b'.d": "\\implicantedge{1}{3}{9}{11}",     
     "b'.d'": " \implicantcorner{0}{2}", 
     # c       
     "c.d": "\\implicant{3}{11}",     
     "c.d'":"\\implicant{2}{10}", 
          
     "c'.d": "\\implicant{1}{9}",     
     "c'.d'":"\\implicant{0}{8}",  
     #d
     # Three variables
     # a
     "a.b.c": "\\implicant{15}{14}",     
     "a.b.c'": "\\implicant{12}{13}",     
     "a.b.d": "\\implicant{13}{15}",     
     "a.b.d'": "\\implicantedge{12}{12}{14}{14}", 
     
     "a.b'.c": "\\implicant{10}{11}",
     "a.b'.c'": "\\implicant{8}{9}",     
     "a.b'.d": "\\implicant{9}{11}",     
     "a.b'.d'": "\\implicantedge{8}{8}{10}{10}", 
      
     "a.c.d": "\\implicant{15}{11}",     
     "a.c.d'": "\\implicant{14}{10}",     
     "a.c'.d": "\\implicant{13}{9}",     
     "a.c'.d'": "\\implicant{12}{8}",      
     # a'
     "a'.b.c": "\\implicant{7}{6}",     
     "a'.b.c'": "\\implicant{4}{5}",     
     "a'.b.d": "\\implicant{5}{7}",     
     "a'.b.d'": "\\implicantedge{4}{4}{6}{6}", 
     
     "a'.b'.c": "\\implicant{3}{2}",     
     "a'.b'.c'": "\\implicant{0}{1}",     
     "a'.b'.d": "\\implicant{1}{3}",     
     "a'.b'.d'": "\\implicantedge{0}{0}{2}{2}",       

     "a'.c.d": "\\implicant{3}{7}",     
     "a'.c.d'": "\\implicant{2}{6}",     
     "a'.c'.d": "\\implicant{1}{5}",     
     "a'.c'.d'": "\\implicant{0}{4}",      
      
     "b.c.d": "\\implicant{7}{15}",     
     "b.c.d'": "\\implicant{6}{14}",     
     "b.c'.d": "\\implicant{5}{13}",     
     "b.c'.d'": "\\implicant{4}{12}",      
      
     "b'.c.d": "\\implicantedge{3}{3}{11}{11}",     
     "b'.c.d'": "\\implicantedge{2}{2}{10}{10}",     
     "b'.c'.d": "\\implicantedge{1}{1}{9}{9}",     
     "b'.c'.d'": "\\implicantedge{0}{0}{8}{8}",      
    # Four vars
    "a'.b'.c'.d'": "\\implicant{0}{0}",
    "a'.b'.c'.d": "\\implicant{1}{1}",
    "a'.b'.c.d'": "\\implicant{2}{2}",
    "a'.b'.c.d": "\\implicant{3}{3}",
    "a'.b.c'.d'": "\\implicant{4}{4}",
    "a'.b.c'.d": "\\implicant{5}{5}",
    "a'.b.c.d'": "\\implicant{6}{6}",
    "a'.b.c.d": "\\implicant{7}{7}",
    "a.b'.c'.d'": "\\implicant{8}{8}",
    "a.b'.c'.d": "\\implicant{9}{9}",
    "a.b'.c.d'": "\\implicant{10}{10}",
    "a.b'.c.d": "\\implicant{11}{11}",
    "a.b.c'.d'": "\\implicant{12}{12}",
    "a.b.c'.d": "\\implicant{13}{13}",
    "a.b.c.d'": "\\implicant{14}{14}",
    "a.b.c.d": "\\implicant{15}{15}", 
   
}

TEX_REDUCTION_TABLE_POS={
    "a":"\\implicant{0}{6}",
    "b":"\\implicantedge{0}{2}{8}{10}",
    "c":"\\implicant{0}{9}",
    "d":"\\implicantedge{0}{8}{2}{10}",
    "a'":"\\implicant{12}{10}",
    "b'":"\\implicant{4}{14}",
    "c'":"\\implicant{3}{10}",
    "d'":"\\implicant{1}{11}",
    # two vars
    "a+b":"\\implicant{0}{2}",
    "a+c":"\\implicant{0}{5}",
    "a+d":"\\implicantedge{0}{4}{2}{6}",
    "b+c":"\\implicantedge{0}{1}{8}{9}",
    "b+d":" \implicantcorner{0}{2}",
    "c+d":"\\implicant{0}{8}",
    "a'+b":"\\implicant{8}{10}",
    "a'+c":"\\implicant{12}{9}",
    "a'+d":"\\implicantedge{12}{8}{14}{10}",
    "a+b'":"\\implicant{4}{6}",
    "a+c'":"\\implicant{3}{6}",
    "a+d'":"\\implicant{1}{7}",
    "b'+c":"\\implicant{4}{13}",
    "b'+d":"\\implicantedge{4}{12}{6}{14}",
    "b+c'":"\\implicantedge{3}{2}{11}{10}",
    "b+d'":"\\implicantedge{1}{3}{9}{11}",
    "c'+d":"\\implicant{2}{10}",
    "c+d'":"\\implicant{1}{9}",
    "a'+b'":"\\implicant{12}{14}",
    "a'+c'":"\\implicant{15}{10}",
    "a'+d'":"\\implicant{13}{11}",
    "b'+c'":"\\implicant{7}{14}",
    "b'+d'":"\\implicant{5}{15}",
    "c'+d'":"\\implicant{3}{11}",

    #3 vars
    "a+b+c":"\\implicant{0}{1}",
    "a+b+d":"\\implicantedge{0}{0}{2}{2}",
    "a+c+d":"\\implicant{0}{4}",
    "b+c+d":"\\implicantedge{0}{0}{8}{8}",
    "a'+b+c":"\\implicant{8}{9}",
    "a'+b+d":"\\implicantedge{8}{8}{10}{10}",
    "a'+c+d":"\\implicant{12}{8}",
    "a+b'+c":"\\implicant{4}{5}",
    "a+b'+d":"\\implicantedge{4}{4}{6}{6}",
    "a+b+c'":"\\implicant{3}{2}",
    "a+b+d'":"\\implicant{1}{3}",
    "a+c'+d":"\\implicant{2}{6}",
    "a+c+d'":"\\implicant{1}{5}",
    "b'+c+d":"\\implicant{4}{12}",
    "b+c'+d":"\\implicantedge{2}{2}{10}{10}",
    "b+c+d'":"\\implicantedge{1}{1}{9}{9}",
    "a'+b'+c":"\\implicant{12}{13}",
    "a'+b'+d":"\\implicantedge{12}{12}{14}{14}",
    "a'+b+c'":"\\implicant{10}{10}",
    "a'+b+d'":"\\implicant{9}{11}",
    "a'+c'+d":"\\implicant{14}{10}",
    "a'+c+d'":"\\implicant{13}{9}",
    "a+b'+c'":"\\implicant{7}{6}",
    "a+b'+d'":"\\implicant{5}{7}",
    "a+c'+d'":"\\implicant{3}{7}",
    "b'+c'+d":"\\implicant{6}{14}",
    "b'+c+d'":"\\implicant{5}{13}",
    "b+c'+d'":"\\implicantedge{3}{3}{11}{11}",

    #4 vars
    "a+b+c+d":"\\implicant{0}{0}",
    "a'+b'+c'":"\\implicant{15}{14}",
    "a'+b'+d'":"\\implicant{13}{15}",
    "a'+c'+d'":"\\implicant{15}{11}",
    "b'+c'+d'":"\\implicant{7}{15}",
    "a+b+c+d'":"\\implicant{1}{1}",
    "a+b+c'+d":"\\implicant{2}{2}",
    "a+b'+c+d":"\\implicant{4}{4}",
    "a'+b+c+d":"\\implicant{8}{8}",
    "a+b+c'+d'":"\\implicant{3}{3}",
    "a+b'+c+d'":"\\implicant{5}{5}",
    "a+b'+c'+d":"\\implicant{6}{6}",
    "a'+b+c+d'":"\\implicant{9}{9}",
    "a'+b+c'+d":"\\implicant{10}{10}",
    "a'+b'+c+d":"\\implicant{12}{12}",
    "a+b'+c'+d'":"\\implicant{7}{7}",
    "a'+b+c'+d'":"\\implicant{11}{11}",
    "a'+b'+c+d'":"\\implicant{13}{13}",
    "a'+b'+c'+d":"\\implicant{14}{14}",
    "a'+b'+c'+d'":"\\implicant{15}{15}",
}

HTML_REDUCTION_TABLE={
	"a":	([12, 10], "implicant"),
	"a'":	([0, 6], "implicant"),
	"b":	([4, 14], "implicant"),
	"b'":	([0, 2, 8, 10], "edge"),
	"c":	([3, 10], "implicant"),
	"c'":	([0, 9], "implicant"),
	"d":	([1, 11], "implicant"),
	"d'":	([0, 8, 2, 10], "edge"),
	"a.b":	([12, 14], "implicant"),
	"a.b'":	([8, 10], "implicant"),
	"a.c":	([15, 10], "implicant"),
	"a.c'":	([12, 9], "implicant"),
	"a.d":	([13, 11], "implicant"),
	"a.d'":	([12, 8, 14, 10], "edge"),
	"a'.b":	([4, 6], "implicant"),
	"a'.b'":	([0, 2], "implicant"),
	"a'.c":	([3, 6], "implicant"),
	"a'.c'":	([0, 5], "implicant"),
	"a'.d":	([1, 7], "implicant"),
	"a'.d'":	([0, 4, 2, 6], "edge"),
	"b.c":	([7, 14], "implicant"),
	"b.c'":	([4, 13], "implicant"),
	"b.d":	([5, 15], "implicant"),
	"b.d'":	([4, 12, 6, 14], "edge"),
	"b'.c":	([3, 2, 11, 10], "edge"),
	"b'.c'":	([0, 1, 8, 9], "edge"),
	"b'.d":	([1, 3, 9, 11], "edge"),
	"b'.d'":	([0, 2, 8, 10], "corner"),
	"c.d":	([3, 11], "implicant"),
	"c.d'":	([2, 10], "implicant"),
	"c'.d":	([1, 9], "implicant"),
	"c'.d'":	([0, 8], "implicant"),
	"a.b.c":	([15, 14], "implicant"),
	"a.b.c'":	([12, 13], "implicant"),
	"a.b.d":	([13, 15], "implicant"),
	"a.b.d'":	([12, 12, 14, 14], "edge"),
	"a.b'.c":	([10, 11], "implicant"),
	"a.b'.c'":	([8, 9], "implicant"),
	"a.b'.d":	([9, 11], "implicant"),
	"a.b'.d'":	([8, 8, 10, 10], "edge"),
	"a.c.d":	([15, 11], "implicant"),
	"a.c.d'":	([14, 10], "implicant"),
	"a.c'.d":	([13, 9], "implicant"),
	"a.c'.d'":	([12, 8], "implicant"),
	"a'.b.c":	([7, 6], "implicant"),
	"a'.b.c'":	([4, 5], "implicant"),
	"a'.b.d":	([5, 7], "implicant"),
	"a'.b.d'":	([4, 4, 6, 6], "edge"),
	"a'.b'.c":	([3, 2], "implicant"),
	"a'.b'.c'":	([0, 1], "implicant"),
	"a'.b'.d":	([1, 3], "implicant"),
	"a'.b'.d'":	([0, 0, 2, 2], "edge"),
	"a'.c.d":	([3, 7], "implicant"),
	"a'.c.d'":	([2, 6], "implicant"),
	"a'.c'.d":	([1, 5], "implicant"),
	"a'.c'.d'":	([0, 4], "implicant"),
	"b.c.d":	([7, 15], "implicant"),
	"b.c.d'":	([6, 14], "implicant"),
	"b.c'.d":	([5, 13], "implicant"),
	"b.c'.d'":	([4, 12], "implicant"),
	"b'.c.d":	([3, 3, 11, 11], "edge"),
	"b'.c.d'":	([2, 2, 10, 10], "edge"),
	"b'.c'.d":	([1, 1, 9, 9], "edge"),
	"b'.c'.d'":	([0, 0, 8, 8], "edge"),
	"a'.b'.c'.d'":	([0, 0], "implicant"),
	"a'.b'.c'.d":	([1, 1], "implicant"),
	"a'.b'.c.d'":	([2, 2], "implicant"),
	"a'.b'.c.d":	([3, 3], "implicant"),
	"a'.b.c'.d'":	([4, 4], "implicant"),
	"a'.b.c'.d":	([5, 5], "implicant"),
	"a'.b.c.d'":	([6, 6], "implicant"),
	"a'.b.c.d":	([7, 7], "implicant"),
	"a.b'.c'.d'":	([8, 8], "implicant"),
	"a.b'.c'.d":	([9, 9], "implicant"),
	"a.b'.c.d'":	([10, 10], "implicant"),
	"a.b'.c.d":	([11, 11], "implicant"),
	"a.b.c'.d'":	([12, 12], "implicant"),
	"a.b.c'.d":	([13, 13], "implicant"),
	"a.b.c.d'":	([14, 14], "implicant"),
	"a.b.c.d":	([15, 15], "implicant"),
}


HTML_REDUCTION_TABLE_POS={
    # 1 var
    "a":	([0, 6], "implicant"),
    "b":	([0, 2, 8, 10], "edge"),
    "c":	([0, 9], "implicant"),
    "d":	([0, 8, 2, 10], "edge"),
    "a'":	([12, 10], "implicant"),
    "b'":	([4, 14], "implicant"),
    "c'":	([3, 10], "implicant"),
    "d'":	([1, 11], "implicant"),

    # 2 vars
    "a+b":	([0, 2], "implicant"),
    "a+c":	([0, 5], "implicant"),
    "a+d":	([0, 4, 2, 6], "edge"),
    "b+c":	([0, 1, 8, 9], "edge"),
    "b+d":	([0, 2], "corner"),
    "c+d":	([0, 8], "implicant"),
    "a'+b":	([8, 10], "implicant"),
    "a'+c":	([12, 9], "implicant"),
    "a'+d":	([12, 8, 14, 10], "edge"),
    "a+b'":	([4, 6], "implicant"),
    "a+c'":	([3, 6], "implicant"),
    "a+d'":	([1, 7], "implicant"),
    "b'+c":	([4, 13], "implicant"),
    "b'+d":	([4, 12, 6, 14], "edge"),
    "b+c'":	([3, 2, 11, 10], "edge"),
    "b+d'":	([1, 3, 9, 11], "edge"),
    "c'+d":	([2, 10], "implicant"),
    "c+d'":	([1, 9], "implicant"),
    "a'+b'":	([12, 14], "implicant"),
    "a'+c'":	([15, 10], "implicant"),
    "a'+d'":	([13, 11], "implicant"),
    "b'+c'":	([7, 14], "implicant"),
    "b'+d'":	([5, 15], "implicant"),
    "c'+d'":	([3, 11], "implicant"),

    # 3 vars
    "a+b+c":	([0, 1], "implicant"),
    "a+b+d":	([0, 0, 2, 2], "edge"),
    "a+c+d":	([0, 4], "implicant"),
    "b+c+d":	([0, 0, 8, 8], "edge"),
    "a'+b+c":	([8, 9], "implicant"),
    "a'+b+d":	([8, 8, 10, 10], "edge"),
    "a'+c+d":	([12, 8], "implicant"),
    "a+b'+c":	([4, 5], "implicant"),
    "a+b'+d":	([4, 4, 6, 6], "edge"),
    "a+b+c'":	([3, 2], "implicant"),
    "a+b+d'":	([1, 3], "implicant"),
    "a+c'+d":	([2, 6], "implicant"),
    "a+c+d'":	([1, 5], "implicant"),
    "b'+c+d":	([4, 12], "implicant"),
    "b+c'+d":	([2, 2, 10, 10], "edge"),
    "b+c+d'":	([1, 1, 9, 9], "edge"),
    "a'+b'+c":	([12, 13], "implicant"),
    "a'+b'+d":	([12, 12, 14, 14], "edge"),
    "a'+b+c'":	([10, 10], "implicant"),
    "a'+b+d'":	([9, 11], "implicant"),
    "a'+c'+d":	([14, 10], "implicant"),
    "a'+c+d'":	([13, 9], "implicant"),
    "a+b'+c'":	([7, 6], "implicant"),
    "a+b'+d'":	([5, 7], "implicant"),
    "a+c'+d'":	([3, 7], "implicant"),
    "b'+c'+d":	([6, 14], "implicant"),
    "b'+c+d'":	([5, 13], "implicant"),
    "b+c'+d'":	([3, 3, 11, 11], "edge"),

    # 4 vars
    "a+b+c+d":	([0, 0], "implicant"),
    "a'+b'+c'":	([15, 14], "implicant"),
    "a'+b'+d'":	([13, 15], "implicant"),
    "a'+c'+d'":	([15, 11], "implicant"),
    "b'+c'+d'":	([7, 15], "implicant"),
    "a+b+c+d'":	([1, 1], "implicant"),
    "a+b+c'+d":	([2, 2], "implicant"),
    "a+b'+c+d":	([4, 4], "implicant"),
    "a'+b+c+d":	([8, 8], "implicant"),
    "a+b+c'+d'":	([3, 3], "implicant"),
    "a+b'+c+d'":	([5, 5], "implicant"),
    "a+b'+c'+d":	([6, 6], "implicant"),
    "a'+b+c+d'":	([9, 9], "implicant"),
    "a'+b+c'+d":	([10, 10], "implicant"),
    "a'+b'+c+d":	([12, 12], "implicant"),
    "a+b'+c'+d'":	([7, 7], "implicant"),
    "a'+b+c'+d'":	([11, 11], "implicant"),
    "a'+b'+c+d'":	([13, 13], "implicant"),
    "a'+b'+c'+d":	([14, 14], "implicant"),
    "a'+b'+c'+d'":	([15, 15], "implicant"),
}
def main(args):
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
